// US ZIP codes, resolved offline from data/us-zip-codes.tsv.gz (GeoNames, CC BY
// 4.0; regenerated by scripts/build-zip-codes.js). No geocoding service is
// called at runtime. The table is read and indexed on the first lookup, which
// happens only when a reader signs up or changes their ZIP.
import fs from "node:fs";
import zlib from "node:zlib";

// Listed in vercel.json's includeFiles so the function bundle carries it.
const TABLE = new URL("../data/us-zip-codes.tsv.gz", import.meta.url);

export const ZIP_FORMAT_MESSAGE = "Enter a 5-digit US ZIP code.";
export const ZIP_UNKNOWN_MESSAGE = "We don't recognise that ZIP code. Check it and try again.";

let table = null;
let places = null;

function load() {
  if (table) return table;
  table = new Map();
  for (const line of zlib.gunzipSync(fs.readFileSync(TABLE)).toString("utf8").split("\n")) {
    if (!line) continue;
    const [zip, latitude, longitude, place] = line.split("\t");
    table.set(zip, { latitude: Number(latitude), longitude: Number(longitude), place });
  }
  return table;
}

// Place name -> [longitude, latitude]: the mean of the place's ZIP code points.
function placeIndex() {
  if (places) return places;
  const sums = new Map();
  for (const { latitude, longitude, place } of load().values()) {
    const sum = sums.get(place) ?? { latitude: 0, longitude: 0, count: 0 };
    sum.latitude += latitude;
    sum.longitude += longitude;
    sum.count += 1;
    sums.set(place, sum);
  }
  const round = (degrees) => Math.round(degrees * 1000) / 1000;
  places = new Map();
  for (const [place, sum] of sums) {
    places.set(place, [round(sum.longitude / sum.count), round(sum.latitude / sum.count)]);
  }
  return places;
}

/** The 5-digit ZIP in `input` ("12345" or ZIP+4 "12345-6789"), or null. */
export function normalizeZip(input) {
  if (typeof input !== "string") return null;
  const match = /^(\d{5})(?:-\d{4})?$/.exec(input.trim());
  return match ? match[1] : null;
}

/**
 * Where `input` is: `{ zip, place, point }`, `place` for display ("Brooklyn,
 * NY") and `point` a GeoJSON Point, or null for anything that is not a known US
 * ZIP code.
 */
export function lookupZip(input) {
  const zip = normalizeZip(input);
  const entry = zip && load().get(zip);
  if (!entry) return null;
  return {
    zip,
    place: entry.place,
    point: { type: "Point", coordinates: [entry.longitude, entry.latitude] },
  };
}

/**
 * Where the map puts `place` ("Brooklyn, NY"): `[longitude, latitude]`, the
 * mean of that place's ZIP code points, or null for a name the table does not
 * have. It depends on the place name alone, so it tells no one more than the
 * name does, even for a place with a single ZIP code.
 */
export function placePoint(place) {
  return placeIndex().get(place) ?? null;
}
